name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --save-dev jest eslint eslint-config-airbnb-base
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test
