name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --save-dev
      - name: Grant write permissions to node_modules (if necessary)
        run: chmod -R u+w node_modules
      - name: Run tests
        run: sudo npm test

